<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Dessert</name>
   <tag></tag>
   <elementGuidId>8e696a6a-b925-48c6-b266-d6ab5f550dca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d71d014e-bd41-4abc-ab30-8013d7d809dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Snack.html</value>
      <webElementGuid>f5e3637a-b805-4794-bc20-35dc80b81670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leftbar-item</value>
      <webElementGuid>0d4965f7-8c39-4242-b4c4-706229829622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dessert</value>
      <webElementGuid>20fa4eab-484c-40f3-96bb-f67ca12fe2e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container1&quot;]/div[@class=&quot;leftbar row&quot;]/a[@class=&quot;leftbar-item&quot;]</value>
      <webElementGuid>2f0a86d0-b671-4874-bf8d-1a27717b9bb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Dessert')]</value>
      <webElementGuid>06f32214-5fd6-4b40-9f43-913429326464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Specials Menu'])[1]/following::a[1]</value>
      <webElementGuid>63eedf3a-1cc2-4ca9-bf68-999e2db51fd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LOCATION'])[1]/following::a[2]</value>
      <webElementGuid>010e5d64-6948-4d72-866c-f2bf000468ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sushi'])[1]/preceding::a[1]</value>
      <webElementGuid>f0a980a2-f665-4692-b2cd-74399c3ba07d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drinks'])[1]/preceding::a[2]</value>
      <webElementGuid>e406d496-334d-4de8-8cec-ff24d5369f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dessert']/parent::*</value>
      <webElementGuid>ab19bebc-f935-413e-b2b6-791cb0590fb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'Snack.html')]</value>
      <webElementGuid>3bfdf4f5-0a5c-4d33-ad5b-b2d3b028e004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>c120c292-b77f-4d18-8607-994d79650b44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'Snack.html' and (text() = 'Dessert' or . = 'Dessert')]</value>
      <webElementGuid>1d63934f-c9dc-4f6c-b2cc-c4e70fd58fea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
