<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sushi</name>
   <tag></tag>
   <elementGuidId>e206e62f-cd59-4dca-b42a-6db4b5953844</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Sushi')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d50a975e-58e9-49cf-a3be-0a8a568082f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Sushi.html</value>
      <webElementGuid>6484cc09-57f4-48c7-9885-39448cc7fc27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leftbar-item</value>
      <webElementGuid>66f88ffa-a6b9-41fe-af7e-1e7604b7136c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sushi</value>
      <webElementGuid>5aba655b-f7ca-4369-b042-c665744bbb73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container1&quot;]/div[@class=&quot;leftbar row&quot;]/a[@class=&quot;leftbar-item&quot;]</value>
      <webElementGuid>cd8097a0-ff21-4f9e-8970-5416000033ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sushi')]</value>
      <webElementGuid>80f0b7f9-10b7-4e1c-9d4c-71633fb213ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dessert'])[1]/following::a[1]</value>
      <webElementGuid>60c8572f-f366-4aa6-9ee6-e3dbce47d376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Specials Menu'])[1]/following::a[2]</value>
      <webElementGuid>9265f5c5-d2a8-48ad-a264-dd72c8b5e440</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drinks'])[1]/preceding::a[1]</value>
      <webElementGuid>c311caef-519e-4253-8ec9-5bbbf2b71b60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sushi']/parent::*</value>
      <webElementGuid>88c6a5a9-031f-4572-bb83-32e56f2108bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'Sushi.html')]</value>
      <webElementGuid>c1f60b9e-3658-4092-8383-e9624b71e723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>4ff7e28f-5f68-4160-9510-bec3d7b10035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'Sushi.html' and (text() = 'Sushi' or . = 'Sushi')]</value>
      <webElementGuid>99580e34-99e7-4f68-8d3b-db6d4a6feadd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
