<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email address_floatingPassword</name>
   <tag></tag>
   <elementGuidId>1d15eeef-b360-4ae5-94b0-1d4a4bf8b4d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#floatingPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='floatingPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b5096c62-fbcd-4976-bc03-f89f5fb32262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>ff66e4d8-ce3f-4d25-858e-6f0d86ca0b6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-light</value>
      <webElementGuid>3a1e4765-77bb-4a76-b116-ffaf0ecca2e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>floatingPassword</value>
      <webElementGuid>8f30caae-fea5-45a9-a25b-53c2e742d53b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>9b5e2e35-3e30-4933-92e5-ff474c0bacce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;floatingPassword&quot;)</value>
      <webElementGuid>a5dfe047-ec05-4228-b1bc-d28a94368200</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='floatingPassword']</value>
      <webElementGuid>66177122-5ad7-4587-8ab6-3bff4a0a85cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Backg']/div[2]/main/form/div[2]/input</value>
      <webElementGuid>c0edb792-5046-4764-9cd7-ae32a92011b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>d1c8bd8a-355a-4232-bd87-bedc29f71c99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'floatingPassword' and @placeholder = 'Password']</value>
      <webElementGuid>cec01d5a-8d7a-4b0e-a975-e143d153326e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
